version = 1

[merge]
automerge_label = "merge it 😤"
method = "squash"
delete_branch_on_merge = true
prioritize_ready_to_merge = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["renovate"]

[approve]
auto_approve_usernames = ["renovate"]
